version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running Maven build to create JAR"
      - mvn clean package
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 779846822985.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t amcart/service-repo .
      - docker tag amcart/service-repo:latest 779846822985.dkr.ecr.ap-south-1.amazonaws.com/amcart/service-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 779846822985.dkr.ecr.ap-south-1.amazonaws.com/amcart/service-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"amcart-product-service","imageUri":"779846822985.dkr.ecr.ap-south-1.amazonaws.com/amcart/service-repo:latest"}]' > imagedefinitions.json
      #- echo Updating ECS Service...
      #- aws ecs update-service --cluster AmcartCluster --service amcart-product-service --force-new-deployment
artifacts:
  files:
    - imagedefinitions.json