package com.nagp.products.entity;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Products") // Replace "Products" with your actual table name
@Data
public class Product {

    @DynamoDBHashKey(attributeName = "product_id")
    //@DynamoDBAutoGeneratedKey
    private String productId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "price")
    private Double price;

    @DynamoDBAttribute(attributeName = "category")
    private String category;

    @DynamoDBAttribute(attributeName = "sub_category")
    private String subCategory;

    @DynamoDBAttribute(attributeName = "stock")
    private Integer stock;

    @DynamoDBAttribute(attributeName = "rating")
    private Double rating;

    @DynamoDBAttribute(attributeName = "color")
    private List<String> color;

    @DynamoDBAttribute(attributeName = "size")
    private List<String> size;

    @DynamoDBAttribute(attributeName = "attributes")
    private Map<String, String> attributes;

    @DynamoDBAttribute(attributeName = "images")
    private List<String> images;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_at")
    private String createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_at")
    private String updatedAt;

    @DynamoDBAttribute(attributeName = "label")
    private String label;

}

